package cn.qtech.mapper;

import cn.qtech.domain.PaperCategory;

import java.util.List;

public interface PaperCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_category
     *
     * @mbggenerated Tue Mar 21 14:23:05 CST 2017
     */
    int deleteByPrimaryKey(String catagoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_category
     *
     * @mbggenerated Tue Mar 21 14:23:05 CST 2017
     */
    int insert(PaperCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_category
     *
     * @mbggenerated Tue Mar 21 14:23:05 CST 2017
     */
    int insertSelective(PaperCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_category
     *
     * @mbggenerated Tue Mar 21 14:23:05 CST 2017
     */
    PaperCategory selectByPrimaryKey(String catagoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_category
     *
     * @mbggenerated Tue Mar 21 14:23:05 CST 2017
     */
    int updateByPrimaryKeySelective(PaperCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_category
     *
     * @mbggenerated Tue Mar 21 14:23:05 CST 2017
     */
    int updateByPrimaryKey(PaperCategory record);

    List<PaperCategory> queryAll();
}
