package cn.qtech.domain;

public class PaperWithBLOBs extends Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.content
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.answer
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.content
     *
     * @return the value of paper.content
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.content
     *
     * @param content the value for paper.content
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.answer
     *
     * @return the value of paper.answer
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.answer
     *
     * @param answer the value for paper.answer
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}