package cn.qtech.domain;

import java.util.Date;

public class Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.user_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_category
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private Integer paperCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.page_difficulty
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private Integer pageDifficulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.create_time
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.title
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.name
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_id
     *
     * @return the value of paper.paper_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_id
     *
     * @param paperId the value for paper.paper_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId == null ? null : paperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.user_id
     *
     * @return the value of paper.user_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.user_id
     *
     * @param userId the value for paper.user_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_category
     *
     * @return the value of paper.paper_category
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public Integer getPaperCategory() {
        return paperCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_category
     *
     * @param paperCategory the value for paper.paper_category
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setPaperCategory(Integer paperCategory) {
        this.paperCategory = paperCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.page_difficulty
     *
     * @return the value of paper.page_difficulty
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public Integer getPageDifficulty() {
        return pageDifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.page_difficulty
     *
     * @param pageDifficulty the value for paper.page_difficulty
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setPageDifficulty(Integer pageDifficulty) {
        this.pageDifficulty = pageDifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.create_time
     *
     * @return the value of paper.create_time
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.create_time
     *
     * @param createTime the value for paper.create_time
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.title
     *
     * @return the value of paper.title
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.title
     *
     * @param title the value for paper.title
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.name
     *
     * @return the value of paper.name
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.name
     *
     * @param name the value for paper.name
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}